version: '3.1'

volumes:
  db:

services:

  postgres:
    image: postgres:alpine3.16
    ports:
      - 8002:5432
    environment:
      POSTGRES_PASSWORD: postgres123456
    volumes:
      - db:/var/lib/postgresql/data
      - ./database/postgres:/docker-entrypoint-initdb.d
      
  redis:
    image: redis:7.0.4
    ports:
      - 8003:6379
