package config

const (
	TASKS_ENABLED = "TASKS_ENABLED"

	JWT_SECRET = "JWT_SECRET"

	DB_SERVER   = "DB_SERVER"
	DB_PORT     = "DB_PORT"
	DB_USER     = "DB_USER"
	DB_PASSWORD = "DB_PASSWORD"
	DB_NAME     = "DB_NAME"

	REPOSITORY_TYPE = "REPOSITORY_TYPE"

	REDIS_ADDR     = "REDIS_ADDR"
	REDIS_PASSWORD = "REDIS_PASSWORD"
	REDIS_DB       = "REDIS_DB"

	CACHE_TYPE = "CACHE_TYPE"

	USER_INIT_USD_AMOUNT = "USER_INIT_USD_AMOUNT"

	SERVER_PORT = "SERVER_PORT"
)
